
POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
    "username": "ashok3",
    "password": "ashok123"
}

####
POST http://localhost:5000/api/users/signin
Content-Type: application/json

{
    "username": "ashok3",
    "password": "ashok123"
}


####
POST http://localhost:5000/api/appointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhc2hvazMiLCJpYXQiOjE3MTk1NzY2ODMsImV4cCI6MTcxOTU4MDI4M30.KZeTAIM8_kfFQbc9r_0kRJpBVBMwpcjCUDwG1Q0OeNc
Content-Type: application/json

{
    "date": "2024-06-27T10:00:00Z",
    "description": "Doctor appointment"
}

###
GET http://localhost:5000/api/appointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhc2hvazMiLCJpYXQiOjE3MTk1NzY2ODMsImV4cCI6MTcxOTU4MDI4M30.KZeTAIM8_kfFQbc9r_0kRJpBVBMwpcjCUDwG1Q0OeNc